[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"

[build]
rustflags = []
incremental = true

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
